outputPath: "{sourceDirPath}\\{sourceName}{targetExtension}"
schemaMapping:
  "*.bmp*": ..\..\..\Sample\bmp.xml
excel:
  fontFamily: Consolas
  headerColor: SkyBlue
  enableAutoFilter: true
  freezePanes: true
  bypassIfRawAvailable: false
