outputPath: "{sourceDirPath}\\{sourceName}{targetExtension}"
schemaMapping:
  "*.bmp": ..\..\..\Sample\bmp.xml
  "*.bmp.xlsx": ..\..\..\Sample\bmp.xml
excel:
  enableAutoFilter: true
  fontFamily: Consolas
  headerColor: SkyBlue
  